---
title: "ISLR_chap1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# import files for ISL_R

```{r load ISLR}
install.packages("ISLR")
```

# Chapter 2

```{r}
x <- c(1,3,2,5)
x
```

```{r}
x = c(1,6,2)
x
y = c(1,4,3)
```

```{r}
length(x)
length(y)
x+y
```

```{r}
ls()
rm(x,y)
ls()
```

```{r}
rm(list=ls())
```

```{r}
?matrix
```

```{r}
x = matrix(data=c(1,2,3,4), nrow=2, ncol=2)
x
```

```{r}
x = matrix(c(1,2,3,4), 2, 2)
x
```

```{r}
matrix(c(1,2,3,4), 2, 2, byrow = TRUE)
```

```{r}
sqrt(x)
x^2
```

```{r}
x = rnorm(50)
x

y = x + rnorm(50, mean=50, sd=.1)
cor(x,y)
```

```{r}
set.seed(1303)
y=rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)
```

```{r}
x = rnorm(100)
y = rnorm(100)
plot(x, y)
plot(x, y, xlab="x-axis", ylab="y-axis", main="title")
```

```{r}
pdf("figure_p46.pdf")
plot(x, y, col="green")
dev.off()
```

```{r}
x = seq(1, 10)
x
x = 1:10
x
x=seq(-pi, pi, length=50)
x
```

```{r}
?contour
```

```{r}
y = x
f = outer(x, y, function(x, y)cos(y)/(1+x^2))
contour(x, y, f)
contour(x, y, f, nlevels=45, add=T)
fa = (f - t(f))/2
contour(x, y, fa, nlevels = 15)
```

```{r}
image(x,y,fa)
persp(x,y,fa)
persp(x,y,fa, theta=30)
persp(x,y,fa, theta=30, phi=20)
persp(x,y,fa, theta=30, phi=70)
persp(x,y,fa, theta=30, phi=40)
```

```{r}
A = matrix(1:16, 4,4)
A
A[2,3]
```

```{r}
A[c(1,3),c(2,4)]
A[1:3, 2:4]
A[1:2,]
A[,1:2]
```

```{r}
A[1,]
A[-c(1,3),]
A[-c(1,3), -c(1,3,4)]
dim(A)
```

```{r}
Auto = read.table("Auto.data", header=TRUE, na.strings = "?")
fix(Auto)
```

```{r}
Auto = read.csv("Auto.csv", header = TRUE, na.strings = "?")
fix(Auto)
dim(Auto)
```

```{r}
Auto[1:4,]
dim(Auto)
Auto = na.omit(Auto)
dim(Auto)
```

```{r}
names(Auto)
```

```{r}
attach(Auto)
plot(cylinders, mpg)
```

```{r}
cylinders = as.factor(cylinders)
```

```{r}
plot(cylinders, mpg)
plot(cylinders, mpg, col="red")
plot(cylinders, mpg, col="red", varwidth=T)
plot(cylinders, mpg, col="red", varwidth=T, horizontal=T)
plot(cylinders, mpg, col="red", varwidth=T, xlab="cylinders", ylab="mpg")
```

```{r}
hist(mpg)
hist(mpg, col=2)
hist(mpg, col=2, breaks = 15)
```

```{r}
pairs(Auto)
pairs( ~ mpg + displacement + horsepower + weight + acceleration, Auto)
```

```{r}
plot(horsepower, mpg)
identify(horsepower, mpg, name)
```

```{r}
summary(Auto)
```

```{r}
summary(mpg)
```















